# Generated by Django 6.0.1 on 2026-02-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
