# Generated by Django 6.0.1 on 2026-02-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ocorrencia_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=20),
        ),
    ]
