# Generated by Django 6.0.1 on 2026-02-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ocorrencia_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='local',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('resolvida', 'Resolvida')], default='pendente', max_length=20),
        ),
    ]
