# Generated by Django 6.0.1 on 2026-02-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ocorrencia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
